language: node_js
node_js:
  - "node"

before_script:
  - tiddlywiki --version
  - pwd
  - ls

script: tiddlywiki ./*wiki --version --verbose --build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master

branches:
  only:
    - master
