language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
  - tiddlywiki --version
  - pwd
  - ls
script: tiddlywiki ./*wiki --build

after_success:
  - bash ./publish.sh

branches:
  only:
    - master
